# Prometheus configuration for CAFA-5 MLOps solution
global:
  scrape_interval: 30s # scrape interval for Prometheus
  evaluation_interval: 30s # evaluation interval for Prometheus
  scrape_timeout: 5s # scrape timeout for Prometheus

rule_files:
  - /etc/prometheus/alerts.yml # alerts file for Prometheus configuration in container

scrape_configs:
  - job_name: prometheus # job name for Prometheus
    static_configs:
      - targets: ["localhost:9090"] # targets for Prometheus

  - job_name: embedding_api_health # job name for embedding API health
    metrics_path: /api/v1/health # metrics path for embedding API health
    static_configs:
      - targets: ["embedding-api:8000"] # targets for embedding API

  - job_name: go_prediction_api_health
    metrics_path: /health # metrics path for GO prediction API health
    static_configs:
      - targets: ["go-prediction-api:8000"] # targets for GO prediction API

  - job_name: trainer_api_health # job name for trainer API health
    metrics_path: /api/train/health # metrics path for trainer API health
    static_configs:
      - targets: ["trainer-api:8000"] # targets for trainer API

  - job_name: mlflow_health
    metrics_path: /health # metrics path for MLflow health
    static_configs:
      - targets: ["mlflow:5000"] # targets for MLflow

  - job_name: embedding_api_metrics # job name for embedding API metrics
    metrics_path: /metrics # metrics path for embedding API metrics
    static_configs:
      - targets: ["embedding-api:8000"] # targets for embedding API

  - job_name: go_prediction_api_metrics
    metrics_path: /metrics # metrics path for GO prediction API metrics
    static_configs:
      - targets: ["go-prediction-api:8000"] # targets for GO prediction API

  - job_name: trainer_api_metrics # job name for trainer API metrics
    metrics_path: /metrics # metrics path for trainer API metrics
    static_configs:
      - targets: ["trainer-api:8000"] # targets for trainer API